### ISSUE TITLE
Extension in lens kept on showing initialising.

### ISSUE THREAD

**Issue by siva143sp** [kubescape/lens-extension#5]
Hi,

I am using Mac SO: catalina 10.15.7 intel i9
Lens: 5.5.4-latest.20220609.2
 trying to add the extension and was able to add and it was showing the version 0.1.9 has been installed and enabled.

Once I connected to the cluster I was able to see the kubescape extesion. when I click on the its kept on showing initialising.
When I click on the any of the resource to see the scape, its shows the below,

<img width="1591" alt="image" src="https://user-images.githubusercontent.com/42701505/181223343-dada611c-4a55-4f81-b0ca-1cb7d15c4d0a.png">

I also i tried multiple time by clearing off the cache of the lens etc..,

Also please find the data in the extension json files
<img width="1516" alt="image" src="https://user-images.githubusercontent.com/42701505/181225072-7d91a0a3-e9ac-439d-b7d7-d4a244e4c74a.png">

Would you kindly help me out to sort this out.

Thanks in advanced! 
Shiva.B

**Comment by amirmalka** [comment]
@siva143sp From the output of `kubescape-preference-store.json` it does look like the extension wasn't installed properly

I suggest to run the commands below in your terminal, which will remove the files and open up Lens from the terminal.
While the terminal is open, you should see Lens startup logs, as well as Kubescape logs or errors if there are any, so I would start troubleshooting from there.


```
rm -rf ~/Library/Application\ Support/Lens/extension-store/@kubescape/lens-extension/kubescape-report-store.json
rm -rf ~/Library/Application\ Support/Lens/extension-store/@kubescape/lens-extension/kubescape-preference-store.json
/Applications/Lens.app/Contents/MacOS/Lens
```

**Comment by siva143sp** [comment]
@amirmalka : thanks much for the response. please find the logs after executing the give commands,

:~ shiva_bhimireddy$ rm -rf ~/Library/Application\ Support/Lens/extension-store/@kubescape/lens-extension/kubescape-preference-store.json
:~ shiva_bhimireddy$ rm -rf ~/Library/Application\ Support/Lens/extension-store/@kubescape/lens-extension/kubescape-report-store.json
:~ shiva_bhimireddy$ /Applications/Lens.app/Contents/MacOS/Lens
info:    ▪ 📟 Setting Lens as protocol client for lens:// +0ms
info:    ▪ 📟 Protocol client register succeeded ✅ +2ms
info:    ▪ [EXTENSIONS-STORE]: LOADING from  ... +14ms
info:    ▪ [EXTENSIONS-STORE]: LOADED from /Users/shiva_bhimireddy/Library/Application Support/Lens/lens-extensions.json +9ms
info:    ▪ [FILESYSTEM-PROVISIONER-STORE]: LOADING from  ... +8ms
info:    ▪ [FILESYSTEM-PROVISIONER-STORE]: LOADED from /Users/shiva_bhimireddy/Library/Application Support/Lens/lens-filesystem-provisioner-store.json +6ms
info:    ▪ 🚀 Starting Lens from "/Applications/Lens.app/Contents/MacOS/Lens" +9ms
info:    ▪ 🐚 Syncing shell environment +0ms
:~ shiva_bhimireddy$

**Comment by siva143sp** [comment]
Its also happening same with the latest version 2 as well.


Component stack:


    at d (/Users/shiva_bhimireddy/.k8slens/extensions/kubescape--lens-extension/dist/renderer.js:1:33486)
    at Details
    at div
    at div
    at div
    at DefaultedAnimate (http://44c5f39c67dfcf1f727ee6ecca508f88.localhost:61032/build/Lens.js?efb54d12584c4a7a3002:575192:9)
    at NonInjectedAnimate
    at NonInjectedDrawer (http://44c5f39c67dfcf1f727ee6ecca508f88.localhost:61032/build/Lens.js?efb54d12584c4a7a3002:594452:9)
    at NonInjectedKubeObjectDetails (http://44c5f39c67dfcf1f727ee6ecca508f88.localhost:61032/build/Lens.js?efb54d12584c4a7a3002:605946:9)
    at ObserverComponent (http://44c5f39c67dfcf1f727ee6ecca508f88.localhost:61032/build/Lens.js?efb54d12584c4a7a3002:240519:23)
    at ErrorBoundary (http://44c5f39c67dfcf1f727ee6ecca508f88.localhost:61032/build/Lens.js?efb54d12584c4a7a3002:594915:9)
    at observerComponent (http://44c5f39c67dfcf1f727ee6ecca508f88.localhost:61032/build/Lens.js?efb54d12584c4a7a3002:240471:16)
    at ThemeProvider (http://44c5f39c67dfcf1f727ee6ecca508f88.localhost:61032/build/Lens.js?efb54d12584c4a7a3002:124521:24)
    at Router (http://44c5f39c67dfcf1f727ee6ecca508f88.localhost:61032/build/Lens.js?efb54d12584c4a7a3002:457461:30)
Error stack:

TypeError: Cannot read properties of undefined (reading 'controls')
    at d.render (/Users/shiva_bhimireddy/.k8slens/extensions/kubescape--lens-extension/dist/renderer.js:1:33585)
    at qi (http://44c5f39c67dfcf1f727ee6ecca508f88.localhost:61032/build/Lens.js?efb54d12584c4a7a3002:456004:188)
    at pi (http://44c5f39c67dfcf1f727ee6ecca508f88.localhost:61032/build/Lens.js?efb54d12584c4a7a3002:456003:173)
    at ck (http://44c5f39c67dfcf1f727ee6ecca508f88.localhost:61032/build/Lens.js?efb54d12584c4a7a3002:456086:427)
    at bk (http://44c5f39c67dfcf1f727ee6ecca508f88.localhost:61032/build/Lens.js?efb54d12584c4a7a3002:456067:347)
    at ak (http://44c5f39c67dfcf1f727ee6ecca508f88.localhost:61032/build/Lens.js?efb54d12584c4a7a3002:456067:278)
    at Tj (http://44c5f39c67dfcf1f727ee6ecca508f88.localhost:61032/build/Lens.js?efb54d12584c4a7a3002:456067:138)
    at Lj (http://44c5f39c67dfcf1f727ee6ecca508f88.localhost:61032/build/Lens.js?efb54d12584c4a7a3002:456060:163)
    at http://44c5f39c67dfcf1f727ee6ecca508f88.localhost:61032/build/Lens.js?efb54d12584c4a7a3002:455940:115
    at exports.unstable_runWithPriority (http://44c5f39c67dfcf1f727ee6ecca508f88.localhost:61032/build/Lens.js?efb54d12584c4a7a3002:471047:343)

**Comment by 963230432** [comment]
> 你好，
> 
> 我正在使用 Mac SO: catalina 10.15.7 intel i9 Lens: 5.5.4-latest.20220609.2 尝试添加扩展并且能够添加并且显示版本 0.1.9 已安装并启用。
> 
> 一旦我连接到集群，我就能看到 kubescape 扩展。当我点击它时，它一直在显示初始化。 当我单击任何资源以查看景观时，它显示如下，
> 
> <img alt="图片" width="1591" src="https://user-images.githubusercontent.com/42701505/181223343-dada611c-4a55-4f81-b0ca-1cb7d15c4d0a.png">
> 
> 我也通过清除镜头的缓存等多次尝试，
> 
> 也请在扩展 json 文件中找到数据 <img alt="图片" width="1516" src="https://user-images.githubusercontent.com/42701505/181225072-7d91a0a3-e9ac-439d-b7d7-d4a244e4c74a.png">
> 
> 你能帮我解决这个问题吗？
> 
> 先谢谢了！ 湿婆

me too

**Comment by 963230432** [comment]
me too

**Comment by amirmalka** [comment]
@siva143sp please advise if the issue persists with the new version of the extension

**Comment by siva143sp** [comment]
This seems to be fixed, thanks much!

Thanks,
Best Regards,
Shiva.B
________________________________

**Comment by amirmalka** [comment]
@siva143sp Thanks for the feedback!
